[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && pnpm install"
]

[phases.build]
cmds = [
  "cd frontend && pnpm run build"
]

[start]
cmd = "cd backend && node server.js"

[build]
copyFiles = [
  { from = "backend", to = "/app/backend" },
  { from = "frontend/dist", to = "/app/frontend/dist" }
]